# -*- coding: utf-8 -*-
{
    'name': "Rental Management - CORETAX e-Faktur (Indonesia)",
    'summary': "Export customer tax invoices to CORETAX Faktur Pajak Keluaran bulk XML.",
    'author': "System Analyst (companion to TechKhedut rental_management)",
    'category': 'Accounting/Localizations',
    'version': "19.0.1.0.0",
    'depends': ['rental_management', 'account'],
    'data': [
        'security/ir.model.access.csv',
        'report/pph42_summary_templates.xml',
        'views/res_partner_views.xml',
        'views/account_move_views.xml',
        'views/product_views.xml',
        'views/tax_registers_views.xml',
        'wizard/coretax_export_views.xml',
        'wizard/coretax_batch_faktur_views.xml',
        'wizard/pph42_summary_wizard_views.xml',
        'views/menus.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'application': False,
    'auto_install': False,
}
