# -*- coding: utf-8 -*-
import json
from markupsafe import Markup
from odoo import api, fields, models


class PropertyReportSnapshot(models.Model):
    """Permanent snapshot of an Owners Statement, saved at print/generate time."""
    _name = 'property.report.snapshot'
    _description = 'Owners Statement Snapshot'
    _order = 'date_generated desc, id desc'

    name = fields.Char(string='Reference', required=True, copy=False,
                       default=lambda s: s.env._('New'))
    property_id = fields.Many2one('property.details', string='Property',
                                  required=True, ondelete='restrict')
    date_from = fields.Date(string='Period From', required=True)
    date_to = fields.Date(string='Period To', required=True)
    date_generated = fields.Datetime(string='Generated On',
                                     default=fields.Datetime.now, readonly=True)
    generated_by = fields.Many2one('res.users', string='Generated By',
                                   default=lambda s: s.env.user, readonly=True)
    data_json = fields.Text(string='Snapshot Data (JSON)', readonly=True)
    summary_html = fields.Html(string='Ringkasan Snapshot', compute='_compute_summary_html', sanitize=False)
    company_id = fields.Many2one(related='property_id.company_id', store=True)

    @api.depends('data_json')
    def _compute_summary_html(self):
        for rec in self:
            try:
                d = json.loads(rec.data_json or '{}')
            except Exception:
                rec.summary_html = Markup('<p>Data tidak tersedia.</p>')
                continue
            rec.summary_html = Markup(rec._build_summary_html(d))

    def _build_summary_html(self, d):
        def th(txt, align='left'):
            return f'<th style="padding:4px 8px;border-bottom:1px solid #ccc;text-align:{align};background:#f5f5f5">{txt}</th>'

        def td(txt, align='left', bold=False, color=''):
            style = f'padding:4px 8px;text-align:{align};'
            if bold:
                style += 'font-weight:bold;'
            if color:
                style += f'color:{color};'
            return f'<td style="{style}">{txt}</td>'

        def section(title, color='#1F3964'):
            return f'<tr><td colspan="9" style="padding:6px 8px 2px;font-weight:bold;font-size:13px;color:{color};border-top:2px solid {color}">{title}</td></tr>'

        def table_open():
            return '<table style="width:100%;border-collapse:collapse;font-size:12px;margin-bottom:16px">'

        html = []

        # ── 1. INFO HEADER ──────────────────────────────────────────────
        html.append('<div style="display:flex;gap:32px;margin-bottom:12px;flex-wrap:wrap">')
        info_items = [
            ('Periode', d.get('period_label', '')),
            ('Manajer', d.get('manager', '')),
            ('Telepon', d.get('phone', '')),
        ]
        owners = d.get('owners', [])
        if owners:
            info_items.append(('Pemilik', ', '.join(f"{o.get('name','')} ({o.get('pct','')})"
                                                    for o in owners)))
        for label, val in info_items:
            html.append(f'<div><span style="color:#666;font-size:11px">{label}</span>'
                        f'<div style="font-weight:bold">{val or "—"}</div></div>')
        html.append('</div>')

        # ── 2. RINGKASAN KINERJA ─────────────────────────────────────────
        perf = d.get('perf', {})
        rows = perf.get('accrual_rows', [])
        net = perf.get('net_return', {})
        if rows:
            html.append('<div style="font-weight:bold;font-size:13px;color:#1F3964;'
                        'border-bottom:2px solid #1F3964;margin-bottom:4px">'
                        '1. Ringkasan Kinerja</div>')
            html.append(table_open())
            html.append('<thead><tr>')
            for h, a in [('Keterangan', 'left'), ('Aktual (P)', 'right'), ('Anggaran (P)', 'right'),
                         ('Selisih', 'right'), ('Aktual (YTD)', 'right'), ('Anggaran (YTD)', 'right'),
                         ('Selisih YTD', 'right')]:
                html.append(th(h, a))
            html.append('</tr></thead><tbody>')
            for r in rows:
                html.append('<tr>')
                html.append(td(r.get('label', '')))
                html.append(td(r.get('c_act', ''), 'right'))
                html.append(td(r.get('c_bud', ''), 'right'))
                html.append(td(r.get('c_var', ''), 'right'))
                html.append(td(r.get('y_act', ''), 'right'))
                html.append(td(r.get('y_bud', ''), 'right'))
                html.append(td(r.get('y_var', ''), 'right'))
                html.append('</tr>')
            if net:
                html.append('<tr style="border-top:2px solid #000;font-weight:bold;background:#d1fae5">')
                html.append(td(net.get('label', 'NET RETURN'), bold=True))
                html.append(td(net.get('c_act', ''), 'right', bold=True))
                html.append(td(net.get('c_bud', ''), 'right', bold=True))
                html.append(td(net.get('c_var', ''), 'right', bold=True))
                html.append(td(net.get('y_act', ''), 'right', bold=True))
                html.append(td(net.get('y_bud', ''), 'right', bold=True))
                html.append(td(net.get('y_var', ''), 'right', bold=True))
                html.append('</tr>')
            html.append('</tbody></table>')

        # ── 3. TOTAL PENDAPATAN & PENGELUARAN ────────────────────────────
        ie = d.get('income_exp', {})
        if ie:
            html.append('<div style="font-weight:bold;font-size:13px;color:#1F3964;'
                        'border-bottom:2px solid #1F3964;margin-bottom:4px">'
                        '2. Pendapatan &amp; Pengeluaran</div>')
            html.append(table_open())
            html.append('<thead><tr>')
            for h, a in [('Keterangan', 'left'), ('Aktual (P)', 'right'),
                         ('Aktual (YTD)', 'right'), ('Anggaran Tahunan', 'right')]:
                html.append(th(h, a))
            html.append('</tr></thead><tbody>')
            for sec in ie.get('sections', []):
                html.append(f'<tr style="background:#e2e8f0"><td colspan="4" style="'
                            f'padding:4px 8px;font-weight:bold">{sec.get("label","")}</td></tr>')
                for grp in sec.get('groups', []):
                    html.append(f'<tr style="background:#f0f0f0"><td colspan="4" style="'
                                f'padding:3px 8px 3px 16px;font-style:italic">{grp.get("label","")}</td></tr>')
                    for row in grp.get('rows', []):
                        html.append('<tr>')
                        html.append(td(f"{row.get('code','')} {row.get('name','')}".strip(),
                                       'left'))
                        html.append(td(row.get('c_act', ''), 'right'))
                        html.append(td(row.get('y_act', ''), 'right'))
                        html.append(td(row.get('a_bud', ''), 'right'))
                        html.append('</tr>')
                    sub = grp.get('sub', {})
                    html.append('<tr style="font-weight:bold;border-top:1px solid #ccc">')
                    html.append(td(f"Subtotal {grp.get('label','')}", bold=True))
                    html.append(td(sub.get('c_act', ''), 'right', bold=True))
                    html.append(td(sub.get('y_act', ''), 'right', bold=True))
                    html.append(td(sub.get('a_bud', ''), 'right', bold=True))
                    html.append('</tr>')
            for label, key, color in [
                ('TOTAL PENDAPATAN', 'total_income', '#dbeafe'),
                ('TOTAL PENGELUARAN', 'total_expense', '#fee2e2'),
                ('LABA BERSIH', 'net_return', '#d1fae5'),
            ]:
                val = ie.get(key, {})
                html.append(f'<tr style="font-weight:bold;background:{color};border-top:2px solid #000">')
                html.append(td(label, bold=True))
                html.append(td(val.get('c', val.get('c_act', '')), 'right', bold=True))
                html.append(td(val.get('y', val.get('y_act', '')), 'right', bold=True))
                html.append(td(val.get('a', val.get('a_bud', '')), 'right', bold=True))
                html.append('</tr>')
            html.append('</tbody></table>')

        # ── 4. SALDO PENYEWA ─────────────────────────────────────────────
        tenants = d.get('tenants', {})
        tenant_rows = tenants.get('rows', [])
        if tenant_rows:
            html.append('<div style="font-weight:bold;font-size:13px;color:#1F3964;'
                        'border-bottom:2px solid #1F3964;margin-bottom:4px">'
                        '3. Saldo Penyewa</div>')
            html.append(table_open())
            html.append('<thead><tr>')
            for h, a in [('Penyewa', 'left'), ('Saldo Awal', 'right'), ('Tagihan', 'right'),
                         ('Penerimaan', 'right'), ('Saldo Akhir', 'right'), ('Deposit', 'right')]:
                html.append(th(h, a))
            html.append('</tr></thead><tbody>')
            for t in tenant_rows:
                html.append('<tr>')
                html.append(td(t.get('name', '')))
                html.append(td(t.get('beginning', ''), 'right'))
                html.append(td(t.get('recurring', ''), 'right'))
                html.append(td(t.get('receipts', ''), 'right'))
                html.append(td(t.get('ending', ''), 'right'))
                html.append(td(t.get('secdep', ''), 'right'))
                html.append('</tr>')
            tot = tenants.get('totals', {})
            html.append('<tr style="font-weight:bold;border-top:2px solid #000;background:#f5f5f5">')
            html.append(td('TOTAL', bold=True))
            html.append(td(tot.get('beginning', ''), 'right', bold=True))
            html.append(td(tot.get('recurring', ''), 'right', bold=True))
            html.append(td(tot.get('receipts', ''), 'right', bold=True))
            html.append(td(tot.get('ending', ''), 'right', bold=True))
            html.append(td(tot.get('secdep', ''), 'right', bold=True))
            html.append('</tr></tbody></table>')

        # ── 5. TUNGGAKAN ─────────────────────────────────────────────────
        arrears = d.get('arrears', {})
        arr_rows = arrears.get('rows', [])
        if arr_rows:
            html.append('<div style="font-weight:bold;font-size:13px;color:#1F3964;'
                        'border-bottom:2px solid #1F3964;margin-bottom:4px">'
                        '4. Tunggakan (Aged Arrears)</div>')
            html.append(table_open())
            html.append('<thead><tr>')
            for h, a in [('Penyewa', 'left'), ('Berjalan', 'right'), ('1-30 Hari', 'right'),
                         ('31-60 Hari', 'right'), ('61-90 Hari', 'right'),
                         ('&gt;90 Hari', 'right'), ('Total', 'right')]:
                html.append(th(h, a))
            html.append('</tr></thead><tbody>')
            for r in arr_rows:
                html.append('<tr>')
                for k in ['name', 'current', 'm1', 'm2', 'm3', 'm4', 'total']:
                    html.append(td(r.get(k, ''), 'right' if k != 'name' else 'left'))
                html.append('</tr>')
            tot = arrears.get('totals', {})
            html.append('<tr style="font-weight:bold;border-top:2px solid #000;background:#f5f5f5">')
            html.append(td('TOTAL', bold=True))
            for k in ['current', 'm1', 'm2', 'm3', 'm4', 'total']:
                html.append(td(tot.get(k, ''), 'right', bold=True))
            html.append('</tr></tbody></table>')

        return ''.join(html)

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if vals.get('name', 'New') in ('New', self.env._('New')):
                vals['name'] = self.env['ir.sequence'].next_by_code(
                    'property.report.snapshot') or '/'
        return super().create(vals_list)

    def get_data(self):
        """Return the snapshot data as a Python dict."""
        self.ensure_one()
        return json.loads(self.data_json) if self.data_json else {}

    @api.model
    def save_snapshot(self, property_id, date_from, date_to, data):
        """Save a snapshot. ``data`` is the dict returned by _compute_data(),
        serialised to JSON (non-serialisable objects are converted to str)."""
        def _safe(obj):
            # date / datetime
            if hasattr(obj, 'isoformat'):
                return obj.isoformat()
            # Odoo recordset — skip, not serialisable
            if hasattr(obj, '_name') and hasattr(obj, 'ids'):
                return None
            return str(obj)

        return self.create({
            'property_id': property_id,
            'date_from': date_from,
            'date_to': date_to,
            'data_json': json.dumps(data, default=_safe),
        })
