# -*- coding: utf-8 -*-
{
    'name': "Rental Management - Property Financial Reports (Owners Statement)",
    'summary': "CBRE/MRI-style Owners Statement suite, Cash Flow Projection & Facility Booking.",
    'author': "System Analyst (companion to TechKhedut rental_management)",
    'category': 'Realestate',
    'version': "19.0.1.0.0",
    'depends': ['rental_management', 'account', 'base_tier_validation', 'purchase'],
    'data': [
        'security/ir.model.access.csv',
        'data/financial_category_data.xml',
        'data/remittance_sequence.xml',
        'data/tier_definition_data.xml',
        'data/management_fee_sequence.xml',
        'report/report_paperformat.xml',
        'report/owner_statement_templates.xml',
        'report/unit_inspection_templates.xml',
        'report/security_deposit_templates.xml',
        'report/clearance_certificate_templates.xml',
        'report/fitout_permit_templates.xml',
        'report/gate_pass_templates.xml',
        'report/cashflow_forecast_templates.xml',
        'report/report_actions.xml',
        'views/financial_category_views.xml',
        'views/property_budget_views.xml',
        'views/property_owner_remittance_views.xml',
        'views/property_security_deposit_views.xml',
        'views/property_details_views.xml',
        'views/account_views.xml',
        'views/purchase_views.xml',
        'views/accrual_template_views.xml',
        'views/management_fee_views.xml',
        'views/period_lock_snapshot_views.xml',
        'views/unit_inspection_views.xml',
        'views/fitout_permit_views.xml',
        'views/gate_pass_views.xml',
        'views/facility_booking_views.xml',
        'wizard/owner_statement_wizard_views.xml',
        'wizard/cashflow_forecast_wizard_views.xml',
        'views/menus.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'application': False,
    'auto_install': False,
}
