# -*- coding: utf-8 -*-
{
    'name': "Rental Management - GTO & Utility Meter",
    'summary': "Gross Turnover Rent (MGR vs GTO), WBP/LWBP peak utility meters, and True-Up settlement.",
    'author': "System Analyst (companion to TechKhedut rental_management)",
    'category': 'Realestate',
    'version': "19.0.1.0.0",
    'depends': ['rental_management', 'account'],
    'data': [
        'security/ir.model.access.csv',
        'data/product_data.xml',
        'data/sequences.xml',
        'data/cron.xml',
        'report/gto_declaration_templates.xml',
        'report/gto_trueup_templates.xml',
        'report/report_actions.xml',
        'views/gto_views.xml',
        'views/meter_views.xml',
        'views/tenancy_gto_views.xml',
        'wizard/meter_bulk_wizard_views.xml',
        'wizard/gto_trueup_wizard_views.xml',
        'views/menus.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'application': False,
}
